/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-01-05 12:39:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mvc.control;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RegisterController_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("import java.io.IOException;\r\n");
      out.write(" \r\n");
      out.write("import javax.servlet.*;\r\n");
      out.write(" \r\n");
      out.write("/**\r\n");
      out.write(" * Servlet implementation class guru_register\r\n");
      out.write(" */\r\n");
      out.write("public class RegisterController extends HttpServlet {\r\n");
      out.write("\tprivate static final long serialVersionUID = 1L;\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("     protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {\r\n");
      out.write("\t\t// TODO Auto-generated method stub\r\n");
      out.write("\t\tString nombre_completo = request.getParameter(\"nombre\") + request.getParameter(\"apellidos\");\r\n");
      out.write("\t\tString mail = request.getParameter(\"correo\");\r\n");
      out.write("\t\tString password = request.getParameter(\"password\");\r\n");
      out.write("\t\tString campo = request.getParameter(\"campo\");\r\n");
      out.write("\t\tString telefono = request.getParameter(\"numero\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(nombre_completo.isEmpty() || mail.isEmpty() || password.isEmpty() || \r\n");
      out.write("\t\t\t\tcampo.isEmpty() || telefono.isEmpty()))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tRequestDispatcher req = request.getRequestDispatcher(\"register_1.jsp\");\r\n");
      out.write("\t\t\treq.include(request, response);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tRequestDispatcher req = request.getRequestDispatcher(\"register_2.jsp\");\r\n");
      out.write("\t\t\treq.forward(request, response);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("}");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
