/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-01-06 13:34:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class privacidad_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.jsp", Long.valueOf(1578316565645L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1578147194546L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/common-head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Política de Privacidad", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t\n");
      out.write("\t\t");
      out.write("<header>\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t    <div class=\"logo circle\" onclick=\"window.location.href='../pages/home.html'\"></div>\n");
      out.write("\t    <nav>\n");
      out.write("\t        <div class=\"col-3\">\n");
      out.write("\t            <a href=\"../pages/perfil-profesional.html\"\n");
      out.write("\t               class=\"button\">ASD</a>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"double-col-3 search-container\">\n");
      out.write("\t            <form action=\"../pages/resultados.html\"\n");
      out.write("\t                  style=\"display: flex\">\n");
      out.write("\t                <input type=\"text\"\n");
      out.write("\t                       placeholder=\"Buscar...\"\n");
      out.write("\t                       name=\"search\">\n");
      out.write("\t                <button type=\"submit\">Enviar</button>\n");
      out.write("\t            </form>\n");
      out.write("\t        </div>\n");
      out.write("\t    </nav>\n");
      out.write("\t</div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Información del perfil -->\n");
      out.write("\t\t<div class=\"container mx-auto flex flex-row mt-3 text-sm leading-normal\">\n");
      out.write("\t\t    <!-- Columna central -->\n");
      out.write("\t\t    <div class=\"w-3/4 mb-4 center\">\n");
      out.write("\t\t        <!-- Sobre mí -->\n");
      out.write("\t\t        <div class=\"caja\">\n");
      out.write("\t\t            <div class=\"titulo-caja\">Política de privacidad</div>\n");
      out.write("\t\t            <div class=\"elemento-caja\">\n");
      out.write("\t\t                <div>\n");
      out.write("\t\t                    <p>\n");
      out.write("\t\t                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisl sem. Maecenas eget tempor sapien, ac\n");
      out.write("\t\t                        rhoncus mi. Suspendisse condimentum tortor vel sapien aliquam, sit amet venenatis est cursus. Mauris mi ligula,\n");
      out.write("\t\t                        sodales quis eros a, varius varius sem. Phasellus a tortor enim. Nam nunc lectus, cursus in luctus quis,\n");
      out.write("\t\t                        consequat at purus. Praesent facilisis justo massa, ut tempor enim condimentum in. Aenean eleifend feugiat nisl,\n");
      out.write("\t\t                        et mattis odio eleifend nec. Suspendisse ex risus, vulputate ac nunc quis, dapibus aliquam nisl.\n");
      out.write("\t\t                    </p>\n");
      out.write("\t\t                    <p>\n");
      out.write("\t\t                        Sed vel massa quis dolor maximus fringilla ut sed nunc. Quisque ornare turpis sit amet odio bibendum rhoncus.\n");
      out.write("\t\t                        Pellentesque placerat arcu ac diam mollis, lobortis gravida elit fermentum. Phasellus eget viverra leo, in\n");
      out.write("\t\t                        eleifend nunc. Aenean vel accumsan metus, non vulputate urna. Praesent sed ante sit amet justo lobortis mattis\n");
      out.write("\t\t                        non eget odio. Nunc nec est efficitur neque eleifend efficitur ac in purus. Donec dui orci, venenatis consequat\n");
      out.write("\t\t                        diam eget, maximus tempor nunc.\n");
      out.write("\t\t                    </p>\n");
      out.write("\t\t                    <ul>\n");
      out.write("\t\t                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>\n");
      out.write("\t\t                        <li>Nulla finibus massa quis orci sollicitudin hendrerit.</li>\n");
      out.write("\t\t                        <li>Donec sit amet purus nec elit feugiat mollis sed eget est.</li>\n");
      out.write("\t\t                    </ul>\n");
      out.write("\t\t                    <p>\n");
      out.write("\t\t                        Nam ac tincidunt ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n");
      out.write("\t\t                        Duis et varius diam. Etiam accumsan, ligula fringilla consectetur volutpat, quam nulla ultricies nunc, nec\n");
      out.write("\t\t                        sollicitudin libero nunc a risus. Praesent quis tortor felis. Nam sed tincidunt orci, at hendrerit sem. In\n");
      out.write("\t\t                        ornare, velit a tristique sollicitudin, orci est vulputate enim, vel rutrum nibh lorem vitae tortor. Aliquam\n");
      out.write("\t\t                        fringilla viverra purus, vitae pulvinar mauris varius quis. Pellentesque quis leo eu quam lacinia cursus. Nullam\n");
      out.write("\t\t                        a cursus mauris, vitae interdum nulla. Vestibulum in scelerisque dolor, nec posuere sapien.\n");
      out.write("\t\t                    </p>\n");
      out.write("\t\t                </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t        </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t");
      out.write("<footer>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-3\">\n");
      out.write("            <a href=\"/pw/about.jsp\" class=\"button\">Sobre nosotros</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-3\">\n");
      out.write("            <a href=\"/pw/terminos.jsp\" class=\"button\">Términos y condiciones de uso</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-3\">\n");
      out.write("            <a href=\"/pw/privacidad.jsp\" class=\"button\">Política de privacidad</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>");
      out.write("\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
